site_name: exerplaza saml documentation

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
    
nav:
  - Home: index.md
  - My Involvement: involvement.md
  - Documentation: documentation.md
