site_name: test

theme:
  name: material
  
features:
  - navigation.sections
  - navigation.expand
  - navigation.tabs
  
nav:
  - Home: index.md
  - My Involvement: involvement.md
  - Documentation: documentation.md
