site_name: exerplaza saml documentation

theme:
  name: material
  palette:
    primary: indigo
    accent: blue

markdown_extensions:
  - pymdownx.superfences

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

nav:
  - Home: index.md
  - My Involvement: involvement.md
  - Setup: setup.md
  - Documentation: documentation.md
